# https://travis-ci.org/#!/translate/translate
language: python
python:
  - 2.6
  - 2.7
  - pypy
env:
  - USECPO=0
  #- USECPO=1
  #- USECPO=2
matrix:
  allow_failures:
    - python: pypy
before_install:
  - sudo apt-get install python-aeidon
install:
  - pip install -r requirements/dev.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install --upgrade --pre lxml; fi
  # Still need to handle with indexing engines
  # docs
  - pip install Sphinx
  # pep8 checks
  - pip install pep8
script:
  # Compile all the files
  - python -m compileall -x '[.]py$' -q -f .
  - py.test -r EfsxX
  - ./tools/pep8.sh travis
  - cd docs; make html
notifications:
  email:
    on_failure: always
    on_success: change
