# https://travis-ci.org/#!/translate/translate
language: python
python:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - pypy
install:
  - pip install --use-mirrors lxml iniparse python-Levenshtein BeautifulSoup
  # Still need to handle with indexing engines and aeidon
script: py.test
