# https://travis-ci.org/#!/translate/translate
language: python
python:
  - 2.6
  - 2.7
  - pypy
env:
  - USECPO=0
  #- USECPO=1
  #- USECPO=2
matrix:
  allow_failures:
    - python: pypy
install:
  - sudo apt-get install python-aeidon
  - pip install --use-mirrors -r requirements/dev.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install --use-mirrors --upgrade --pre lxml; fi
  # Still need to handle with indexing engines
  # docs
  - pip install --use-mirrors Sphinx
  # pep8 checks
  - pip install pep8
script:
  - py.test -r EfsxX
  - ./tools/pep8.sh travis
  - cd docs; make html
notifications:
  email:
    on_failure: always
    on_success: change
